config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: 'static_pages#dashboard', as: :authenticated_root
  end
  
  devise_for :users, controllers: { registrations: 'registrations' }, :path_prefix => "r"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "static_pages#dashboard"
  
  post '/user/update/:id' => 'users#update', :as => :update_user
  post '/users/new' => 'users#create', :as => :create_user
  
  resources :users, except: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    def update_without_password(params, *options)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, :get_data
    
    def get_data
        if user_signed_in?
            @getFName = current_user.fname
            @getLName = current_user.lname
            @getEmail = current_user.email
            @getStreet = current_user.street
            @getState = current_user.state
            @getCity = current_user.city
            @getZip = current_user.zip_code
            @getPhoneNum = current_user.phone_number
        end
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # Before_actions here?
  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    
     respond_to do |format|
      if @user.update_attributes(account_update_params)
        format.html { redirect_to edit_user_registration_path, notice: 'Your account has been updated!' }
        format.json { head :no_content }
      else
        format.html { redirect_to edit_user_registration_path, alert: 'There was an error while updating your account. Please verify all data has been entered correctly.' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
  
  private

  def sign_up_params
    params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :username, :birth_date, :street, :city, :state, :zip_code, :card_num, :phone_number)
  end

  def account_update_params
    params.require(:user).permit(:fname, :lname, :email, :username, :phone_number, :birth_date, :street, :city, :state, :zip_code, :card_num)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :is_allowed, only: [:edit, :update, :show, :destroy]
  before_action :block_access, only: [:index]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  
  def is_allowed
    @user = User.find(params[:id])
    redirect_to root_path unless current_user.id == @user.id
  end
  
  def block_access
    redirect_to root_path
  end
  
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :phone_number, :username, :birth_date, :street, :city, :state, :zip_code, :card_num)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sidenavandheader.html.erb
<!-- page top -->
    <div id="page-header">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <a class="navbar-brand" href="/"><strong><i>hypeBeat</i></strong> &nbsp; <span style="font-size:12px;">Beat the hype.</span></a>
            <ul class="user-top-right-standard user-top-right nav navbar-nav">
              <li class="btn-log">
                <div class="logout-btn">
                  <% if user_signed_in? %>
                    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
                  <% end %>
                  
                </div>
              </li>
            </ul>
            <div style="clear: both;"></div>
          </div>
        </div>
      </div>
    </div>

        <div class="profile-user-details">
          <div class="user-top-right-mobile">
            <li class="btn-log">
              <div class="logout-btn">
                <% if user_signed_in? %>
                  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
                <% end %>
              </div>
            </li>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>hypeBeat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/sidenavandheader' %>
    <%= yield %>
    
    <% unless flash.empty? %>
       <script type="text/javascript">
            <% flash.each do |f| %>
  	      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
  	     	 toastr['<%= type %>']('<%= f[1] %>', '', {"newestOnTop": true, "positionClass": "toast-top-center"});
  	   <% end %>
       </script>
    <% end %>
  </body>
</html>

app/views/static_pages/dashboard.html.erb
<div class="container">
    <br>
           <div class="col-md-6 offset-md-3 profile-box">
               <br>
               <h3 class="h3 text-center">My Info</h2>
               <div class="profile-text">
                   <div class="row">
                    <div class="col-md-6">Name:</div>
                    <div class="col-md-6"><%= @getFName %> <%= @getLName %></div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-6">Email:</div>
                    <div class="col-md-6"><%= @getEmail %></div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-6">Phone Number:</div>
                    <div class="col-md-6"><%= number_to_phone(@getPhoneNum, area_code: true) %></div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-6">Address:</div>
                    <div class="col-md-6"><%= @getStreet %></div>
                </div>
                <div class="row">
                    <div class="col-md-6"></div>
                    <div class="col-md-6"><%= @getCity %>, <%= @getState %></div>
                </div>
                <div class="row">
                    <div class="col-md-6"></div>
                    <div class="col-md-6"><%= @getZip %></div>
                </div>
               </div>
               <br>
               <div class="text-center">
                    <%= link_to 'Edit My Profile', edit_user_path(current_user), :class => "btn btn-sm btn-light" %>
                </div>
                <br>
            </div>
            <br>
            
        <div class="col-md-6 offset-md-3 profile-box">
            <div class="row profile-text">
                <div class="col-md-6">
                    <h4 class="h4 text-center">Item Information</h2>
                    <br>
                    <div class="form-group">
                        <input type="text" name="itemname" placeholder="Item Name" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="text" name="itemcolor" placeholder="Item Color" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="text" name="itemsize" placeholder="Item Size" class="form-control">
                    </div>
                </div>
                <div class="col-md-6">
                    <h4 class="h4 text-center">Credit Card Details</h2>
                    <br>
                    <div class="form-group">
                        <input type="text" name="CCExpireMonth" placeholder="Exp. Month" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="text" name="CCExpireYear" placeholder="Exp. Year" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="text" name="CCCVC" placeholder="CVC" class="form-control">
                    </div>
                </div>
            </div>
            <div class="text-center">
                <input type="submit" value="Start the Bot. Beat the Hype." class="btn btn-primary">
            </div>
            <br>
        </div>
        <br>
</div>

app/views/users/_form.html.erb
<div class="col-md-12">
  <div class="container col-md-8 offset-md-2">
    <%= form_with(model: user, local: true) do |f| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
    
          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="form-group col-md-6">
        <%= f.label "First Name" %><br />
        <%= f.text_field :fname, autocomplete: "off", :required => true, id: :user_fname, :class => 'form-control' %>
      </div>
      
      <div class="form-group col-md-6">
        <%= f.label "Last Name" %><br />
        <%= f.text_field :lname, autocomplete: "off", :required => true, id: :user_lname, :class => 'form-control' %>
      </div>
      
      <div class="form-group col-md-6">
        <%= f.label "Email" %><br />
        <%= f.email_field :email, autocomplete: "off", :required => true, id: :user_email, :class => 'form-control' %>
      </div>
      
      <div class="form-group col-md-6">
        <%= f.label "Bio" %><br />
        <%= f.text_field :bio, autocomplete: "off", :required => true, id: :user_bio, :class => 'form-control' %>
      </div>
      
      <div class="form-group col-md-6">
        <%= f.label "Birthday" %><br />
        <%= f.date_field :birth_date, autocomplete: "off", :required => true, id: :user_birth_date, :class => 'form-control' %>
      </div>
      
      <div class="form-group col-md-6">
        <%= f.label "Favorite Class" %><br />
        <%= f.text_field :favorite_class, autocomplete: "off", :required => true, id: :user_favorite_class, :class => 'form-control' %>
      </div>
      
      <div class="form-group col-md-6">
        <%= f.label "Password" %><br />
        <%= f.text_field :password, autocomplete: "off", :required => true, id: :user_password, :class => 'form-control' %>
      </div>
    
      <div class="form-group actions">
        <%= f.submit "Create User", :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% javascript_include_tag "hide-password" %>
<div class="col-md-12">
  <div class="offset-md-4 col-md-4 container-login">
    <h2 class="h2 text-center">Edit My Profile</h2>
    <br>

    <%= form_for(:user, url: {action: 'update'}, :method => :POST, :html => {:id => 'avatar-form'}) do |f| %>
      
      <div class="form-group">
        <%= f.email_field :email, autofocus: true, autocomplete: "email", :required => true, :placeholder => "Email", :class => "form-control" %>
      </div>
          
      <div class="form-group form-row">
        <div class="col">
          <%= f.text_field :fname, autocomplete: "fname", :required => true, :placeholder => "First Name", :class => "form-control" %>
        </div>
        <div class="col">
          <%= f.text_field :lname, autocomplete: "lname", :required => true, :placeholder => "Last Name", :class => "form-control" %>
        </div>        
      </div>

      <div class="form-group">
        <%= f.text_field :phone_number, autocomplete: "phone_number", :required => true, :placeholder => "Phone Number", :class => "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.text_field :card_num, autofocus: true, autocomplete: "credit card", :required => true, :maxlength => 16, :placeholder => "Credit Card Number", :class => "form-control" %>
        <small id="credHelp" class="form-text text-muted">We store this data. Securely.</small>
      </div>

      <div class="form-group form-row">
        <div class="col">
          <%= f.text_field :street, :required => true, :placeholder => "Street", :class => "form-control" %>
        </div>
        <div class="col">
          <%= f.text_field :city, :required => true, :placeholder => "City", :class => "form-control" %>
        </div>
      </div>

      <div class="form-group form-row">
        <div class="col">
          <%= f.text_field :state, :required => true, :placeholder => "State", :class => "form-control" %>
        </div>
        <div class="col">
          <%= f.text_field :zip_code, :required => true, :placeholder => "Zip Code", :class => "form-control" %>
        </div>
      </div>
      
      <div class="actions">
        <%= f.submit "Update My Account", :class => "btn btn-primary btn-block" %>
      </div>
    <% end %>
    
    <div class="text-center">
      <%= link_to 'Back to My Profile', root_path, :class => 'btn btn-light btn-sm' %> 
    </div>
    <hr>
    <div class="text-center">
      <p>Unhappy with your experience?</p>
      <%= button_to "Close My Account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, :class => "btn btn-danger btn-block" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="col-md-12">
  <div class="container col-md-8 offset-md-2">
    
    <h2 class="h2 text-center">All Users</h2>
    
    <table class="table col-md-10 offset-md-1 text-left">
    
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><strong>Name:</strong> <%= user.fname %> <%= user.lname %></td>
            
            <td><strong>Email:</strong> <%= user.email %></td>
            
            <td>
              <%= link_to 'View Profile', user, :class => "btn btn-sm btn-success" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center">
      <%= link_to 'Logout'.html_safe, destroy_user_session_path, method: :delete, :class => 'btn btn-light btn-sm' %> 
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="col-md-12">
    <h1 class="text-center">New User</h1>

<%= form_for User.new, url: create_user_path, html: {class: "validate"} do |f| %>
  
  <div class="form-group col-md-6">
    <%= f.label "First Name" %><br />
    <%= f.text_field :fname, autocomplete: "off", :required => true, id: :user_fname, :class => 'form-control' %>
  </div>
  
  <div class="form-group col-md-6">
    <%= f.label "Last Name" %><br />
    <%= f.text_field :lname, autocomplete: "off", :required => true, id: :user_lname, :class => 'form-control' %>
  </div>
  
  <div class="form-group col-md-6">
    <%= f.label "Email" %><br />
    <%= f.email_field :email, autocomplete: "off", :required => true, id: :user_email, :class => 'form-control' %>
  </div>
  
  <div class="form-group col-md-6">
    <%= f.label "Bio" %><br />
    <%= f.text_field :bio, autocomplete: "off", :required => true, id: :user_bio, :class => 'form-control' %>
  </div>
  
  <div class="form-group col-md-6">
    <%= f.label "Birthday" %><br />
    <%= f.date_field :birth_date, autocomplete: "off", :required => true, id: :user_birth_date, :class => 'form-control' %>
  </div>
  
  <div class="form-group col-md-6">
    <%= f.label "Favorite Class" %><br />
    <%= f.text_field :favorite_class, autocomplete: "off", :required => true, id: :user_favorite_class, :class => 'form-control' %>
  </div>
  
  <div class="form-group col-md-6">
    <%= f.label "Password" %><br />
    <%= f.text_field :password, autocomplete: "off", :required => true, id: :user_password, :class => 'form-control' %>
  </div>
  
  <%= f.submit "Create User", :class => 'btn btn-info btn-lg' %>
<% end %>

<%= link_to 'Back', users_path, :class => 'btn btn-default' %>
</div>

app/views/users/show.html.erb
<div class="col-md-12">
    <div class="container col-md-8 offset-md-2">
        <h2 class="h2 text-center"><%= @user.fname %> <%= @user.lname %></h2>
        <br>
        <div>
                <p>Email:</p>
                <p><%= @user.email %></p>
                <p>Phone Number:</p>
                <p><%= @user.phone_number%></p>
                <p>Address:</p>
                <p><%= @user.street %></p>
                <p><%= @user.city%>, <%= @user.state%></p>
                <p><%= @user.zip_code %></p>
        </div>
        <div class="text-center">
            <%= link_to 'Back', root_path, :class => "btn btn-light btn-sm" %> 
            <% if @user.id == current_user.id %>
                <%= link_to 'Edit My Profile', edit_user_path(current_user), :class => "btn btn-sm btn-light" %>
            <% else %>
            <% end %>
        </div>
    </div>
</div>
<p id="notice"><%= notice %></p>